---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    name: redis
    author: intelliqit
spec:
  replicas: 2
  selector:
    matchLabels:
      name: redis
  template:
    metadata:
      name: redis-pod
    spec:
      containers:
        - name: myredis
          image: redis
...